insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (1, 'Kirlin-Morissette', 'Ridgeview', '35', 5039, '957-106-6512', 'Indonesia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (2, 'Parker, O''Keefe and Littel', 'Valley Edge', '97274', 9329, '560-453-4390', 'France');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (3, 'Spencer LLC', 'Anthes', '6', 7587, '695-934-5556', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (4, 'Rice, Barton and Raynor', 'Northland', '6', 5114, '363-329-3878', 'Nepal');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (5, 'Harris-Funk', 'Susan', '137', 6358, '397-366-1022', 'Thailand');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (6, 'Howell-Rice', 'Sutherland', '2', 6070, '556-244-9353', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (7, 'Armstrong LLC', 'Westend', '05064', 7637, '135-944-8997', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (8, 'Harvey-Cartwright', 'Glacier Hill', '77', 3363, '566-211-5526', 'Philippines');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (9, 'O''Kon, Rutherford and Hermiston', 'Cascade', '1', 4380, '933-256-6717', 'Russia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (10, 'Hagenes, Johnson and Crooks', 'Pawling', '8315', 5308, '787-671-8230', 'Indonesia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (11, 'Crona LLC', 'Dorton', '82', 5089, '505-533-2035', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (12, 'Goodwin, Goodwin and Rolfson', 'Hanson', '877', 8673, '407-579-1735', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (13, 'Ratke-Hayes', 'Westridge', '29', 3831, '730-778-3824', 'Canada');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (14, 'Hilpert and Sons', 'Grover', '79974', 4850, '798-377-9756', 'Ireland');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (15, 'Moore-Kuvalis', 'Montana', '81', 4601, '944-212-1627', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (16, 'Hermiston Inc', 'Burrows', '299', 9908, '684-568-3354', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (17, 'Terry Group', 'Clemons', '5294', 5558, '351-550-5368', 'Philippines');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (18, 'Gislason-Cruickshank', 'Moland', '1', 8505, '437-716-2553', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (19, 'Parisian, Gulgowski and Abshire', 'Pankratz', '1', 4541, '592-506-6479', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (20, 'Boehm, Huel and Skiles', 'Anthes', '075', 4928, '607-157-0253', 'Czech Republic');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (21, 'Streich-Parker', 'Clove', '7', 4878, '703-621-0211', 'Poland');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (22, 'Mann Group', 'Crowley', '49', 8248, '606-468-4130', 'Sweden');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (23, 'Veum-Kshlerin', 'Norway Maple', '17446', 4670, '534-135-6647', 'Philippines');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (24, 'Roberts, Kertzmann and Turner', 'Linden', '49121', 7182, '599-172-1305', 'Brazil');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (25, 'Nikolaus, Crooks and Olson', 'Duke', '21', 3839, '629-834-0650', 'Italy');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (26, 'Bartoletti-Beatty', 'Lunder', '26', 9697, '145-342-8394', 'Turkey');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (27, 'Streich-Schoen', 'Grover', '567', 9618, '495-394-6691', 'Russia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (28, 'Mraz-Pollich', 'Heath', '3', 2046, '137-413-6858', 'Poland');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (29, 'Streich-Frami', 'Veith', '7', 8502, '465-444-3072', 'Poland');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (30, 'Cassin-Hahn', 'Cottonwood', '8', 2476, '353-662-4763', 'Macedonia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (31, 'Powlowski, Medhurst and Barrows', 'Transport', '3', 4103, '534-778-7829', 'Micronesia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (32, 'Prosacco and Sons', 'Lakewood Gardens', '76', 4828, '326-158-3057', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (33, 'O''Kon and Sons', 'Eggendart', '70813', 2094, '785-454-3887', 'Canada');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (34, 'Corkery-Friesen', 'La Follette', '932', 1354, '501-371-7488', 'Peru');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (35, 'Hodkiewicz, Morissette and Ratke', 'Hayes', '69', 4339, '682-114-4529', 'Ukraine');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (36, 'McKenzie, Mueller and McClure', 'Shelley', '45', 3695, '355-455-2363', 'Colombia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (37, 'Langworth, Abshire and Watsica', 'Norway Maple', '7394', 9254, '968-983-6115', 'Sweden');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (38, 'Swaniawski and Sons', 'Bluejay', '76456', 5098, '544-693-9781', 'Brazil');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (39, 'Lang Group', 'Banding', '03392', 3312, '585-832-4853', 'Brazil');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (40, 'Erdman, Moen and Adams', 'Fairview', '5', 9905, '186-260-2439', 'Slovenia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (41, 'Jakubowski, Flatley and Cremin', 'Schurz', '644', 3194, '786-332-1454', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (42, 'Rowe-Heaney', 'Anhalt', '067', 9959, '811-525-4117', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (43, 'Rodriguez, Rempel and Shields', 'Nevada', '7', 2656, '772-548-9920', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (44, 'Schmeler and Sons', 'Mallard', '7439', 5754, '826-777-9852', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (45, 'Toy, Strosin and Goyette', 'Roxbury', '1', 5895, '249-379-3742', 'Guatemala');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (46, 'King-Kirlin', 'Kenwood', '86', 4234, '304-991-7273', 'Malaysia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (47, 'Nader LLC', 'Manufacturers', '45', 1130, '667-791-1121', 'Indonesia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (48, 'Torphy Group', 'Claremont', '8', 3269, '875-269-5537', 'Panama');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (49, 'Rau, Thiel and Bauch', 'Cordelia', '816', 6372, '622-383-5142', 'Sweden');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (50, 'Considine Group', 'Superior', '82427', 8444, '195-224-5075', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (51, 'Hammes, Nader and Homenick', 'Graceland', '1', 5317, '874-219-7638', 'Kenya');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (52, 'Russel-Swift', 'Mesta', '42981', 6654, '802-186-6391', 'Indonesia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (53, 'Mitchell LLC', 'Waywood', '57', 5564, '344-434-3321', 'Indonesia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (54, 'Sanford, Brown and Smitham', 'Burrows', '6159', 4489, '887-756-3591', 'Argentina');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (55, 'Shanahan and Sons', 'Dottie', '817', 9631, '811-238-3289', 'Indonesia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (56, 'Emard, Kling and Cremin', 'Dunning', '0', 7936, '746-803-2537', 'Brazil');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (57, 'Quigley-Jast', 'Rusk', '3', 5134, '665-711-2466', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (58, 'Goyette-Dicki', 'Caliangt', '4095', 9093, '344-179-7775', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (59, 'Bode, Roberts and Zemlak', 'Boyd', '93', 8166, '396-724-6260', 'Philippines');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (60, 'Watsica Group', 'Prairieview', '0', 4442, '703-477-8215', 'Japan');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (61, 'Kiehn, Weissnat and Beer', 'Green Ridge', '45', 2840, '684-221-9667', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (62, 'Stracke-Reichert', 'Graedel', '8', 3413, '443-189-1578', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (63, 'O''Conner-Windler', 'Carey', '26641', 8972, '253-187-7541', 'Ukraine');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (64, 'Ward-Hickle', 'Packers', '3', 5844, '856-409-2738', 'Japan');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (65, 'Muller Inc', 'Manufacturers', '9615', 7634, '144-202-6339', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (66, 'McDermott and Sons', 'Oak Valley', '983', 8625, '810-241-3991', 'Philippines');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (67, 'Brakus-Johnston', 'Prentice', '44', 6725, '353-284-2969', 'Indonesia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (68, 'Hermiston Group', 'Hanover', '59', 7965, '105-584-4136', 'Mauritania');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (69, 'Feeney, Adams and Haag', 'Johnson', '7', 8295, '341-587-0879', 'Poland');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (70, 'Hane-Hyatt', 'Melvin', '02', 1411, '492-429-7868', 'Indonesia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (71, 'Bechtelar, Pouros and Schaefer', 'Forest Run', '40', 3500, '876-225-3863', 'Indonesia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (72, 'Reichel, Boyer and Prosacco', 'Texas', '38918', 1059, '855-566-1198', 'Lebanon');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (73, 'Effertz and Sons', 'Sherman', '64', 8753, '879-613-9737', 'Greece');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (74, 'Lockman LLC', 'Schurz', '928', 8072, '767-658-7893', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (75, 'Yundt, Simonis and McCullough', 'Mccormick', '38484', 8279, '129-464-6818', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (76, 'Rowe Group', 'Declaration', '2586', 2198, '681-472-3471', 'Indonesia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (77, 'Cormier Group', 'Lerdahl', '29', 2351, '575-176-9435', 'Serbia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (78, 'Koch, Streich and Berge', 'Upham', '7', 3707, '637-806-8588', 'United Kingdom');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (79, 'Marks LLC', 'Gina', '53733', 9736, '855-394-6882', 'Vietnam');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (80, 'Wintheiser, Herzog and Hyatt', 'Mccormick', '25', 2482, '449-438-9523', 'Dominican Republic');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (81, 'Sauer-Crist', 'Anhalt', '584', 3321, '451-486-6690', 'Indonesia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (82, 'Dickinson and Sons', 'Fieldstone', '6424', 9723, '418-585-8307', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (83, 'Pfeffer, Walsh and Kulas', 'Sachs', '271', 5023, '517-693-1484', 'Russia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (84, 'Bergnaum, Swaniawski and Johns', 'Luster', '769', 3454, '265-136-7769', 'Guinea-Bissau');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (85, 'Stroman and Sons', 'Forest Dale', '05', 1712, '293-196-3488', 'Russia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (86, 'Leuschke LLC', 'Butterfield', '4659', 6850, '947-704-3280', 'Cambodia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (87, 'Kub LLC', 'School', '4619', 4094, '847-532-3306', 'Serbia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (88, 'Sporer, Roberts and Homenick', 'Carioca', '18', 3394, '909-910-3845', 'France');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (89, 'Bartell, Reichert and Hills', 'Sauthoff', '086', 4260, '579-781-1888', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (90, 'Roberts Group', 'Kedzie', '6539', 8676, '100-486-4719', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (91, 'Schowalter Group', 'Kinsman', '5', 2401, '405-247-6535', 'France');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (92, 'O''Kon, Altenwerth and Bogan', 'Sachtjen', '60831', 8613, '877-594-2169', 'Indonesia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (93, 'Rogahn Inc', 'Drewry', '3', 7542, '321-258-1970', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (94, 'Corwin-Jacobson', 'Delladonna', '89281', 8980, '926-390-8038', 'Mexico');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (95, 'Tremblay-Price', 'Maywood', '3652', 3123, '737-346-3406', 'Russia');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (96, 'Osinski Group', 'Southridge', '48393', 8099, '315-689-0636', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (97, 'Schumm Inc', 'Morning', '109', 7550, '332-483-0757', 'Portugal');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (98, 'Mosciski-Braun', 'Drewry', '05', 6015, '109-798-9586', 'China');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (99, 'Beahan Group', 'Fremont', '9391', 2308, '340-329-2662', 'Luxembourg');
insert into unternehmen (pk_unternehmenId, u_name, adresse, hausnummer, postleitzahl, telNummer, land) values (100, 'Flatley-Stanton', 'Dapin', '9752', 5336, '615-491-0455', 'Philippines');
